const TO_LOGIN = 'TO LOGIN';
const TO_LOGOUT = 'TO LOGOUT';
const LOGOUT = 'LOGOUT';
const LOGINED = 'LOGINED';
const TO_FETCH_USER_INFO = 'TO FETCH USER INFO';
const USER_INFO_REACHED = 'USER INFO REACHED';
const NO_LOGIN = 'NO LOGIN';

export {
    TO_LOGIN,
    TO_LOGOUT,
    LOGOUT,
    LOGINED,
    TO_FETCH_USER_INFO,
    USER_INFO_REACHED,
    NO_LOGIN
};
